### ISSUE TITLE
Crash into DELL G5 5990

### ISSUE THREAD

**Issue by agodinhost** [HypsyNZ/ISOKIT#3]
It is crashing into a Dell G5 5990.
The initial setup goes well until the first batch script. The first script runs with some errors - I could not get it the error message.
The thing is that some drivers are being installed in background while these scripts are running - I think it is messing up with then somehow.
Maybe it works with internet disabled (that will stop this driver installation)

**Comment by HypsyNZ** [comment]
Some errors are expected because of how I iterated over a couple of things, its fine.

> Maybe it works with internet disabled (that will stop this driver installation)

Installing windows is always better with the internet turned off.

The script will restart the computer when its done, You can proceed as normal from there.
